import './globals.css'
import { Inter } from 'next/font/google'
import { ThemeProvider } from './context/ThemeContext'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ABoard',
  description: 'Generated by ABoard',
}

// This component helps avoid hydration mismatch
function ThemeWrapper({ children }: { children: React.ReactNode }) {
  return (
    <div className="contents">
      {children}
    </div>
  )
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} bg-background-light dark:bg-background-dark text-text-light dark:text-text-dark transition-colors duration-200`}>
        <ThemeProvider>
          <ThemeWrapper>
            {children}
          </ThemeWrapper>
        </ThemeProvider>
      </body>
    </html>
  )
}