import './globals.css'
import { Inter } from 'next/font/google'
import { ThemeProvider } from './context/ThemeContext'
import { UserProvider } from './context/UserContext'
import { BoardProvider } from './context/BoardContext'
import { NoteProvider } from './context/NoteContext'
import { ToDoProvider } from './context/ToDoContext'
import { ModalProvider } from './context/ModalContext'
import { EventProvider } from './context/EventContext'
import NotificationComponent from "@/ui/_Notification/Notification";

import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'  // burada import et

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ABOARD',
  description: 'Generated by ABoard',
}

function ThemeWrapper({ children }: { children: React.ReactNode }) {
  return (
    <div className="contents">
      {children}
    </div>
  )
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} bg-background-light dark:bg-background-dark text-text-light dark:text-text-dark transition-colors duration-200`}>
        <ThemeProvider>
          <UserProvider>
            <BoardProvider>
              <NoteProvider>
                <EventProvider>
                  <ToDoProvider>
                    <ModalProvider>
                      <ThemeWrapper>
                        {children}
                       <NotificationComponent />
                        <ToastContainer 
                          position="top-right" 
                          autoClose={5000} 
                          hideProgressBar={false} 
                          newestOnTop={false} 
                          closeOnClick 
                          rtl={false} 
                          pauseOnFocusLoss 
                          draggable 
                          pauseOnHover 
                          theme="light"
                        />
                      </ThemeWrapper>
                    </ModalProvider>
                  </ToDoProvider>
                </EventProvider>
              </NoteProvider>
            </BoardProvider>
          </UserProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
